// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: submissions/submission.proto

package submissions

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmissionNotif struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FormId        string                 `protobuf:"bytes,3,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
	FormName      string                 `protobuf:"bytes,4,opt,name=form_name,json=formName,proto3" json:"form_name,omitempty"`
	Messages      map[string]string      `protobuf:"bytes,11,rep,name=messages,proto3" json:"messages,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmissionNotif) Reset() {
	*x = SubmissionNotif{}
	mi := &file_submissions_submission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmissionNotif) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmissionNotif) ProtoMessage() {}

func (x *SubmissionNotif) ProtoReflect() protoreflect.Message {
	mi := &file_submissions_submission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmissionNotif.ProtoReflect.Descriptor instead.
func (*SubmissionNotif) Descriptor() ([]byte, []int) {
	return file_submissions_submission_proto_rawDescGZIP(), []int{0}
}

func (x *SubmissionNotif) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SubmissionNotif) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SubmissionNotif) GetFormId() string {
	if x != nil {
		return x.FormId
	}
	return ""
}

func (x *SubmissionNotif) GetFormName() string {
	if x != nil {
		return x.FormName
	}
	return ""
}

func (x *SubmissionNotif) GetMessages() map[string]string {
	if x != nil {
		return x.Messages
	}
	return nil
}

var File_submissions_submission_proto protoreflect.FileDescriptor

const file_submissions_submission_proto_rawDesc = "" +
	"\n" +
	"\x1csubmissions/submission.proto\x12\x17proto.model.submissions\"\x81\x02\n" +
	"\x0fSubmissionNotif\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\aform_id\x18\x03 \x01(\tR\x06formId\x12\x1b\n" +
	"\tform_name\x18\x04 \x01(\tR\bformName\x12R\n" +
	"\bmessages\x18\v \x03(\v26.proto.model.submissions.SubmissionNotif.MessagesEntryR\bmessages\x1a;\n" +
	"\rMessagesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B/Z-github.com/jebing/jform-protos/go/submissionsb\x06proto3"

var (
	file_submissions_submission_proto_rawDescOnce sync.Once
	file_submissions_submission_proto_rawDescData []byte
)

func file_submissions_submission_proto_rawDescGZIP() []byte {
	file_submissions_submission_proto_rawDescOnce.Do(func() {
		file_submissions_submission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_submissions_submission_proto_rawDesc), len(file_submissions_submission_proto_rawDesc)))
	})
	return file_submissions_submission_proto_rawDescData
}

var file_submissions_submission_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_submissions_submission_proto_goTypes = []any{
	(*SubmissionNotif)(nil), // 0: proto.model.submissions.SubmissionNotif
	nil,                     // 1: proto.model.submissions.SubmissionNotif.MessagesEntry
}
var file_submissions_submission_proto_depIdxs = []int32{
	1, // 0: proto.model.submissions.SubmissionNotif.messages:type_name -> proto.model.submissions.SubmissionNotif.MessagesEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_submissions_submission_proto_init() }
func file_submissions_submission_proto_init() {
	if File_submissions_submission_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_submissions_submission_proto_rawDesc), len(file_submissions_submission_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_submissions_submission_proto_goTypes,
		DependencyIndexes: file_submissions_submission_proto_depIdxs,
		MessageInfos:      file_submissions_submission_proto_msgTypes,
	}.Build()
	File_submissions_submission_proto = out.File
	file_submissions_submission_proto_goTypes = nil
	file_submissions_submission_proto_depIdxs = nil
}
